### ISSUE TITLE
X-button href change & to &amp;

### ISSUE THREAD

**Issue by galegobr01** [PH7-Jack/livewire-ui#361]
On inform a href in x-button, if url contains & this is changed to &amp;

1. Add a x-button with a href url with &
2. See the error

**Comment by ph7jack** [comment]
@galegobr01 
Hello, you are probably using the button in this way
```
$url = 'my-url&param=foo';

 <x-button href="{{ $url }}" label="Default" />
```

The blade will encode all things inside the `{{}}` tags to prevent XSS attacks
The correct way to pass a dynamic URL from a variable is giving as a parameter
```
$url = 'my-url&param=foo';

 <x-button :href="$url" label="Default" />
```

I'm closing this issue, if your problem is different tell me to re-open the issue
