### ISSUE TITLE
Breaks breeze login + dashboard logout for me

### ISSUE THREAD

**Issue by l0gical** [PH7-Jack/livewire-ui#474]
Hey all,
Unsure if this is just me but 2x fresh installs of Laravel breeze with Livewire, each time the wireui is installed, the dropdown (top right of dashboard) to logout and the login/reset password buttons become inoperative.
Pretty bummed as built a near complete application around wireui which works great apart from this.
No php errors logged nor anything in apache errors, am running the test sites through Laragon which I solely use for *all* my local dev projects. 

Suggestions welcome, thx

**Comment by l0gical** [comment]
Actually, have done a 3rd install, this time solely using Atom editor rather than VS-Code, exact same setup BUT not linked to Git in any way or form, so far this is running, am just waiting for the menu/logout/login to break but hasn't yet, will update any findings on this.

**Comment by MarcinStefaniak** [comment]
Hi,
I had a similar problem. I managed to solve it as follows.

1. I commented in the app.js file

// import Alpine from 'alpinejs';
// window.Alpine = Alpine;

2. in layouts / app.blade.php
I added at the end of the page

<script defer src = "https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"> </script>

Dropdown started working.

**Comment by l0gical** [comment]
> Hi, I had a similar problem. I managed to solve it as follows.
> 
> 1. I commented in the app.js file
> 
> // import Alpine from 'alpinejs'; // window.Alpine = Alpine;
> 
> 2. in layouts / app.blade.php
>    I added at the end of the page
> 
> <script defer src = "https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"> </script>
> Dropdown started working.

Thanks, will try that and report back with any updates

**Comment by l0gical** [comment]
Hi all,
That appears to have fixed that issue, thank you!

**Comment by rabol** [comment]
well, this is only a 'work-around'

I have the same issue, will there be a 'real' solution ?

**Comment by rabol** [comment]
Another 'work-around' is to 'rename' the dropdown that is installed by Breeze in your resources/views/components directory e.g. breeze-dropdown.blade.php and then modify the resources/views/layouts/navigation.blade.php to use the renamed version.

by renaming, then you have both types of dropdowns available

**Comment by MarcinStefaniak** [comment]
My recent observations show that the problem is solved by importing the js files in the correct order. It is precisely about files that use Alpinejs.

It is important that the code snippet Alpine.start (). it was called last.

i.e., e.g. in the following order:


1. @livewireScript
2. @wireUiScripts

...

78. @vite ('resources / js / app.js')

**Comment by MarcinStefaniak** [comment]
My recent observations show that the problem is solved by importing the js files in the correct order. It is precisely about files that use Alpinejs.

It is important that the code snippet Alpine.start(). was used last.

i.e., e.g. in the following order:


1. @livewireScript
2. @wireUiScripts
...
78. @vite ('resources / js / app.js')
