### ISSUE TITLE
HTML is escaped in label and cornerHint input slots

### ISSUE THREAD

**Issue by frankiejarrett** [PH7-Jack/livewire-ui#581]
**Describe the bug**

The `label` and `cornerHint` input slots should allow HTML markup. It works fine for `hint`, `prepend`, `append` and `suffix`.

In #292 it was specifically advised to use `<x-slot name="cornerHint">` for custom markup, but it doesn't work anymore.

Is this a regression?

**To Reproduce**

```blade
<x-input>
    <x-slot name="label">
        <strong>Label</strong>
    </x-slot>

    <x-slot name="cornerHint">
        <strong>Corner hint</strong>
    </x-slot>
</x-input>
```

<img width="488" alt="Screen Shot 2022-12-19 at 1 24 09 PM" src="https://user-images.githubusercontent.com/522158/208503865-6c5f830d-eb54-44de-9629-14b46098a986.png">

**Expected behavior**

<img width="497" alt="Screen Shot 2022-12-19 at 1 27 26 PM" src="https://user-images.githubusercontent.com/522158/208504457-2e2ed59b-6196-47dd-b548-48ef3a711fd7.png">

**Dependencies**
 - WireUI Version: 1.17.8
 - Laravel Version: 9.44.0
 - Alpine.js Version: 3.10.5
 - Livewire Version: 2.10.7
 - Lang: en_US

**Comment by joaopalopes24** [comment]
@fjarrett Hello. This is not a regression. Components are currently created in a way that slot traversal does not work. This will be completely redone in v2, and will be able to make those customizations. Therefore, I will close the PR because it is not a bug, and these points are already being worked on in v2.
