### ISSUE TITLE
Toggle dropdown not working

### ISSUE THREAD

**Issue by JACarrasco7** [PH7-Jack/livewire-ui#655]
hi, when click the tailwind dropdown not working. I can only see this picture and i can´t see all the dropdown contain 

![dropdown](https://user-images.githubusercontent.com/45757951/235619161-91cf7fb6-cedf-4c12-a485-0614483f3fae.png)

**Comment by JACarrasco7** [comment]
Hi, also the multiple select not working css. I have install all requirements and all links in my app

**Comment by alexcasarrubias** [comment]
This is happeninig because wireui **x-dropdown** component is overriding **livewire native x-dropdown** component.
native component looks like this:
`
<x-dropdown> <x-dropdown-link /></x-dropdown>
`

wire ui component is a bit diferent:
`
<x-dropdown>
    <x-slot name="trigger">
        <x-button label="Options" primary />
    </x-slot> 
    <x-dropdown.item label="Help Center" />
    <x-dropdown.item separator label="Live Chat" />
    <x-dropdown.item separator label="Logout" />
</x-dropdown>
`

To fix it you should change  dropdown.blade.php file to dropdown-native.blade.php(or similar), that way you can use wireui dropdown as `<x-dropdown>` and native livewire component as `<x-dropdown-native>`

A bit tricky, but it worked to me when I renamed the file

Best
