### ISSUE TITLE
V2 Select not set wire model value

### ISSUE THREAD

**Issue by Artessan** [PH7-Jack/livewire-ui#803]
**Describe the bug**
In V2 the select component loose wire model property and has to be place outside of the component

**To Reproduce**
```
<div class="col-span-2 lg:col-span-1">
    <x-select
        label="{{__('Contact type')}}"
        placeholder="{{__('Select one type')}}"
        option-label="label"
        option-value="value"
        :options="[
            ['value' => 'company', 'label' => 'Company'],
            ['value' => 'person' , 'label' => 'Person'],
        ]" wire:model="contactForm.type"/>
</div>
```

the property value is not set in livewire

```
                    <div class="col-span-2 lg:col-span-1" wire:model="contactForm.type">
                        <x-select
                            label="{{__('Contact type')}}"
                            placeholder="{{__('Select one type')}}"
                            option-label="label"
                            option-value="value"
                            :options="[
                                ['value' => 'company', 'label' => 'Company'],
                                ['value' => 'person' , 'label' => 'Person'],
                            ]"/>
                    </div>
```

this works (the model is set outside the component)

**Expected behavior**
Maybe the component should add the given properties as properties of the most external div  as the input is hidden

**Dependencies**
 - WireUI Version: 2.X.X
 - Laravel Version: 10.X.X
 - Alpine.js Version: 3.X.X
 - Livewire Version: 3.X.X

**Comment by BoGnY** [comment]
Same problem, but other than in Select, also even in Select (with async), Currency, DateTimePicker, and maybe other.

**Comment by joaopalopes24** [comment]
Thank you for using WireUi!

We released stable version 2, with new features and improvements. Check if the mentioned problem has been resolved, if not, reopen this issue and we will provide more information. Thank you in advance, we are organizing Issues for better maintenance.

**Comment by mkramek** [comment]
~~I'd like to reopen this issue, as it's still bothering me.~~
~~The issue described here **is actually on version 2**, as stated in the initial report. The basis of this issue is the fact that setting `wire:model` property directly on the `x-select` component does not manipulate the data. No action is being taken there. Is it a bug, or is there a new way, yet to be described in the docs?~~

Edit: I've just checked the logic, and the `wire:model.live` gets the job done. The non-live counterpart does not relay the data on focus change or anything really, but I think since the `select` itself is more client-side-related, `wire:model.live` should do a better job there in general.
