### ISSUE TITLE
Mini Button Icon disappear when clicking other buttons

### ISSUE THREAD

**Issue by Uhasith** [PH7-Jack/livewire-ui#918]
**Describe the bug**

I added spinner to my mini button and passes method name as a prop. But when i click other Buttons mt default icon is disappeaing.

```  <x-wui-mini-button rounded secondary icon="plus" wire:click="addSubTask" spinner="addSubTask" />```

**Screenshots or Videos**

https://github.com/wireui/wireui/assets/78094049/d5aa3200-5780-42c4-ac89-b31c259a6f69

**Dependencies**
 - "wireui/wireui": "^2.0"
 - "laravel/framework": "^11.0",
 -  "livewire/livewire": "^3.4",

**Desktop (If applicable, please complete the following information):**
 - Browser: [chrome]

**Comment by ph7jack** [comment]
Hi @Uhasith , please update your livewire to https://github.com/livewire/livewire/releases/tag/v3.5.1.
Let me know if the issue persists

**Comment by mfazail** [comment]
I have found similar problem when using mini buttons, there is no wire:target in the current icon which is why when any action is called the current icon hides itself.

Code for delete icon:

```blade
<x-mini-button xs
    wire:confirm="Are you sure want to delete team '{{ $team->name }}'?"
    wire:click="deleteTeam({{ $team->id }})"
    spinner="deleteTeam({{ $team->id }})"
    icon="trash" />

```

Preview: all delete icons hides when any actions performed.
![Screenshot 2024-07-13 113844](https://github.com/user-attachments/assets/27888c52-da8f-4691-8c58-180236f81ed3)

**Comment by ph7jack** [comment]
Hi @Uhasith and @mfazail,

Thank you for reporting this issue! I've fixed it, and it will be released later today.
